    const_def
    
    const CACOPHONY
    const STENCH
    const DRIZZLE
    const SPEED_BOOST
    const BATTLE_ARMOR
    const SHELL_ARMOR
    const STURDY
    const DAMP
    const LIMBER
    const SAND_VEIL
    const STATIC
    const VOLT_ABSORB
    const WATER_ABSORB
    const OBLIVIOUS
    const CLOUD_NINE
    const AIR_LOCK
    const COMPOUND_EYES
    const INSOMNIA
    const VITAL_SPIRIT
    const COLOR_CHANGE
    const IMMUNITY
    const FLASH_FIRE
    const SHIELD_DUST
    const OWN_TEMPO
    const SUCTION_CUPS
    const INTIMIDATE
    const SHADOW_TAG
    const ARENA_TRAP
    const ROUGH_SKIN
    const WONDER_GUARD
    const LEVITATE
    const EFFECT_SPORE
    const SYNCHRONIZE
    const CLEAR_BODY
    const WHITE_SMOKE
    const NATURAL_CURE
    const LIGHTNING_ROD
    const SERENE_GRACE
    const SWIFT_SWIM
    const CHLOROPHYLL
    const ILLUMINATE
    const TRACE
    const HUGE_POWER
    const PURE_POWER
    const POISON_POINT
    const INNER_FOCUS
    const MAGMA_ARMOR
    const WATER_VEIL
    const MAGNET_PULL
    const SOUNDPROOF
    const RAIN_DISH
    const SAND_STREAM
    const PRESSURE
    const THICK_FAT
    const EARLY_BIRD
    const FLAME_BODY
    const RUN_AWAY
    const KEEN_EYE
    const HYPER_CUTTER
    const PICKUP
    const TRUANT
    const HUSTLE
    const CUTE_CHARM
    const FORECAST
    const STICKY_HOLD
    const SHED_SKIN
    const GUTS
    const MARVEL_SCALE
    const LIQUID_OOZE
    const OVERGROW
    const BLAZE
    const TORRENT
    const SWARM
    const ROCK_HEAD
    const DROUGHT
    const TANGLED_FEET
    const MOTOR_DRIVE
    const RIVALRY
    const STEADFAST
    const SNOW_CLOAK
    const GLUTTONY
    const ANGER_POINT
    const UNBURDEN
    const HEATPROOF
    const SIMPLE
    const DRY_SKIN
    const DOWNLOAD
    const IRON_FIST
    const POISON_HEAL
    const ADAPTABILITY
    const SKILL_LINK
    const HYDRATION
    const SOLAR_POWER
    const QUICK_FEET
    const NORMALIZE
    const SNIPER
    const MAGIC_GUARD
    const NO_GUARD
    const STALL
    const TECHNICIAN
    const LEAF_GUARD
    const KLUTZ
    const MOLD_BREAKER
    const SUPER_LUCK
    const AFTERMATH
    const ANTICIPATION
    const FOREWARN
    const UNAWARE
    const TINTED_LENS
    const FILTER
    const SOLID_ROCK
    const SLOW_START
    const SCRAPPY
    const STORM_DRAIN
    const ICE_BODY
    const SNOW_WARNING
    const HONEY_GATHER
    const FRISK
    const RECKLESS
    const MULTITYPE
    const FLOWER_GIFT
    const BAD_DREAMS
    const DRAGONS_MAW
    const TRANSISTOR
    const PIXILATE
NUM_ABILITIES EQU const_value
