; sprite_anim_struct members (see macros/ram.asm)
rsreset
DEF SPRITEANIMSTRUCT_INDEX           rb ; 0
DEF SPRITEANIMSTRUCT_FRAMESET_ID     rb ; 1
DEF SPRITEANIMSTRUCT_ANIM_SEQ_ID     rb ; 2
DEF SPRITEANIMSTRUCT_TILE_ID         rb ; 3
DEF SPRITEANIMSTRUCT_XCOORD          rb ; 4
DEF SPRITEANIMSTRUCT_YCOORD          rb ; 5
DEF SPRITEANIMSTRUCT_XOFFSET         rb ; 6
DEF SPRITEANIMSTRUCT_YOFFSET         rb ; 7
DEF SPRITEANIMSTRUCT_DURATION        rb ; 8
DEF SPRITEANIMSTRUCT_DURATIONOFFSET  rb ; 9
DEF SPRITEANIMSTRUCT_FRAME           rb ; a
DEF SPRITEANIMSTRUCT_JUMPTABLE_INDEX rb ; b
DEF SPRITEANIMSTRUCT_VAR1            rb ; c
DEF SPRITEANIMSTRUCT_VAR2            rb ; d
DEF SPRITEANIMSTRUCT_VAR3            rb ; e
DEF SPRITEANIMSTRUCT_VAR4            rb ; f
DEF SPRITEANIMSTRUCT_LENGTH EQU _RS
DEF NUM_SPRITE_ANIM_STRUCTS EQU 10 ; see wSpriteAnimationStructs

; wSpriteAnimDict keys (see wram.asm)
; UnusedSpriteAnimGFX indexes (see data/sprite_anims/unused_gfx.asm)
	const_def
	const SPRITE_ANIM_DICT_DEFAULT      ; 0
	const_skip 4                        ; unused
	const SPRITE_ANIM_DICT_TEXT_CURSOR  ; 5
	const SPRITE_ANIM_DICT_GS_SPLASH    ; 6
	const SPRITE_ANIM_DICT_SLOTS        ; 7
	const SPRITE_ANIM_DICT_ARROW_CURSOR ; 8
DEF NUM_SPRITE_ANIM_GFX EQU const_value

; wSpriteAnimDict size (see wram.asm)
DEF NUM_SPRITEANIMDICT_ENTRIES EQU 10

; SpriteAnimSeqData indexes (see data/sprite_anims/sequences.asm)
	const_def
	const SPRITE_ANIM_INDEX_PARTY_MON                 ; 00
	const SPRITE_ANIM_INDEX_GS_TITLE_TRAIL            ; 01
	const SPRITE_ANIM_INDEX_NAMING_SCREEN_CURSOR      ; 02
	const SPRITE_ANIM_INDEX_GAMEFREAK_LOGO            ; 03
	const SPRITE_ANIM_INDEX_GS_GAMEFREAK_LOGO_STAR    ; 04
	const SPRITE_ANIM_INDEX_GS_GAMEFREAK_LOGO_SPARKLE ; 05
	const SPRITE_ANIM_INDEX_SLOTS_GOLEM               ; 06
	const SPRITE_ANIM_INDEX_SLOTS_CHANSEY             ; 07
	const SPRITE_ANIM_INDEX_SLOTS_EGG                 ; 08
	const SPRITE_ANIM_INDEX_COMPOSE_MAIL_CURSOR       ; 09
	const SPRITE_ANIM_INDEX_RED_WALK                  ; 0a
	const SPRITE_ANIM_INDEX_MEMORY_GAME_CURSOR        ; 0b
	const SPRITE_ANIM_INDEX_POKEGEAR_ARROW            ; 0c
	const SPRITE_ANIM_INDEX_TRADE_POKE_BALL           ; 0d
	const SPRITE_ANIM_INDEX_TRADE_POOF                ; 0e
	const SPRITE_ANIM_INDEX_TRADE_TUBE_BULGE          ; 0f
	const SPRITE_ANIM_INDEX_TRADEMON_ICON             ; 10
	const SPRITE_ANIM_INDEX_TRADEMON_BUBBLE           ; 11
	const SPRITE_ANIM_INDEX_EVOLUTION_BALL_OF_LIGHT   ; 12
	const SPRITE_ANIM_INDEX_RADIO_TUNING_KNOB         ; 13
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_RED          ; 14
	const SPRITE_ANIM_INDEX_LEAF                      ; 15
	const SPRITE_ANIM_INDEX_CUT_TREE                  ; 16
	const SPRITE_ANIM_INDEX_FLY_LEAF                  ; 17
	const SPRITE_ANIM_INDEX_EGG_CRACK                 ; 18
	const SPRITE_ANIM_INDEX_GS_INTRO_HO_OH_LUGIA      ; 19
	const SPRITE_ANIM_INDEX_HEADBUTT                  ; 1a
	const SPRITE_ANIM_INDEX_EGG_HATCH                 ; 1b
	const SPRITE_ANIM_INDEX_EZCHAT_CURSOR             ; 1c
	const SPRITE_ANIM_INDEX_BLUE_WALK                 ; 1d
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_BLUE         ; 1e
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_SENT_BALL    ; 1f
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_OT_BALL      ; 20
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_CABLE_BULGE  ; 21
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_SENT_PULSE   ; 22
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_OT_PULSE     ; 23
	const SPRITE_ANIM_INDEX_MOBILE_TRADE_PING         ; 24
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE             ; 25
	const SPRITE_ANIM_INDEX_INTRO_PICHU               ; 26
	const SPRITE_ANIM_INDEX_INTRO_WOOPER              ; 27
	const SPRITE_ANIM_INDEX_INTRO_UNOWN               ; 28
	const SPRITE_ANIM_INDEX_INTRO_UNOWN_F             ; 29
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE_AWAY        ; 2a
	const SPRITE_ANIM_INDEX_CELEBI                    ; 2b
DEF NUM_SPRITE_ANIM_INDEXES EQU const_value

; DoAnimFrame.Jumptable indexes (see engine/gfx/sprite_anims.asm)
	const_def
	const SPRITE_ANIM_SEQ_NULL                      ; 00
	const SPRITE_ANIM_SEQ_PARTY_MON                 ; 01
	const SPRITE_ANIM_SEQ_PARTY_MON_SWITCH          ; 02
	const SPRITE_ANIM_SEQ_PARTY_MON_SELECTED        ; 03
	const SPRITE_ANIM_SEQ_GS_TITLE_TRAIL            ; 04
	const SPRITE_ANIM_SEQ_NAMING_SCREEN_CURSOR      ; 05
	const SPRITE_ANIM_SEQ_GAMEFREAK_LOGO            ; 06
	const SPRITE_ANIM_SEQ_GS_GAMEFREAK_LOGO_STAR    ; 07
	const SPRITE_ANIM_SEQ_GS_GAMEFREAK_LOGO_SPARKLE ; 08
	const SPRITE_ANIM_SEQ_SLOTS_GOLEM               ; 09
	const SPRITE_ANIM_SEQ_SLOTS_CHANSEY             ; 0a
	const SPRITE_ANIM_SEQ_SLOTS_EGG                 ; 0b
	const SPRITE_ANIM_SEQ_MAIL_CURSOR               ; 0c
	const SPRITE_ANIM_SEQ_MEMORY_GAME_CURSOR        ; 0d
	const SPRITE_ANIM_SEQ_POKEGEAR_ARROW            ; 0e
	const SPRITE_ANIM_SEQ_TRADE_POKE_BALL           ; 0f
	const SPRITE_ANIM_SEQ_TRADE_TUBE_BULGE          ; 10
	const SPRITE_ANIM_SEQ_TRADEMON_IN_TUBE          ; 11
	const SPRITE_ANIM_SEQ_REVEAL_NEW_MON            ; 12
	const SPRITE_ANIM_SEQ_RADIO_TUNING_KNOB         ; 13
	const SPRITE_ANIM_SEQ_CUT_LEAVES                ; 14
	const SPRITE_ANIM_SEQ_FLY_FROM                  ; 15
	const SPRITE_ANIM_SEQ_FLY_LEAF                  ; 16
	const SPRITE_ANIM_SEQ_FLY_TO                    ; 17
	const SPRITE_ANIM_SEQ_GS_INTRO_HO_OH_LUGIA      ; 18
	const SPRITE_ANIM_SEQ_EZCHAT_CURSOR             ; 19
	const SPRITE_ANIM_SEQ_MOBILE_TRADE_SENT_PULSE   ; 1a
	const SPRITE_ANIM_SEQ_MOBILE_TRADE_OT_PULSE     ; 1b
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE             ; 1c
	const SPRITE_ANIM_SEQ_INTRO_PICHU_WOOPER        ; 1d
	const SPRITE_ANIM_SEQ_CELEBI                    ; 1e
	const SPRITE_ANIM_SEQ_INTRO_UNOWN               ; 1f
	const SPRITE_ANIM_SEQ_INTRO_UNOWN_F             ; 20
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE_AWAY        ; 21
DEF NUM_SPRITE_ANIM_SEQS EQU const_value

; SpriteAnimFrameData indexes (see data/sprite_anims/framesets.asm)
	const_def
	const SPRITE_ANIM_FRAMESET_00                        ; 00
	const SPRITE_ANIM_FRAMESET_PARTY_MON                 ; 01
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL       ; 02
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM       ; 03
	const SPRITE_ANIM_FRAMESET_PARTY_MON_FAST            ; 04
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL_FAST  ; 05
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM_FAST  ; 06
	const SPRITE_ANIM_FRAMESET_GS_TITLE_TRAIL            ; 07
	const SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR         ; 08
	const SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR_BIG     ; 09
	const SPRITE_ANIM_FRAMESET_GAMEFREAK_LOGO            ; 0a
	const SPRITE_ANIM_FRAMESET_GS_GAMEFREAK_LOGO_STAR    ; 0b
	const SPRITE_ANIM_FRAMESET_GS_GAMEFREAK_LOGO_SPARKLE ; 0c
	const SPRITE_ANIM_FRAMESET_SLOTS_GOLEM               ; 0d
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY             ; 0e
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY_2           ; 0f
	const SPRITE_ANIM_FRAMESET_SLOTS_EGG                 ; 10
	const SPRITE_ANIM_FRAMESET_RED_WALK                  ; 11
	const SPRITE_ANIM_FRAMESET_STILL_CURSOR              ; 12
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL           ; 13
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL_WOBBLE    ; 14
	const SPRITE_ANIM_FRAMESET_TRADE_POOF                ; 15
	const SPRITE_ANIM_FRAMESET_TRADE_TUBE_BULGE          ; 16
	const SPRITE_ANIM_FRAMESET_TRADEMON_ICON             ; 17
	const SPRITE_ANIM_FRAMESET_TRADEMON_BUBBLE           ; 18
	const SPRITE_ANIM_FRAMESET_EVOLUTION_BALL_OF_LIGHT   ; 19
	const SPRITE_ANIM_FRAMESET_RADIO_TUNING_KNOB         ; 1a
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_RED          ; 1b
	const SPRITE_ANIM_FRAMESET_LEAF                      ; 1c
	const SPRITE_ANIM_FRAMESET_CUT_TREE                  ; 1d
	const SPRITE_ANIM_FRAMESET_EGG_CRACK                 ; 1e
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_1               ; 1f
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_2               ; 20
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_3               ; 21
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_4               ; 22
	const SPRITE_ANIM_FRAMESET_GS_INTRO_HO_OH_LUGIA      ; 23
	const SPRITE_ANIM_FRAMESET_HEADBUTT                  ; 24
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_1           ; 25
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_2           ; 26
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_3           ; 27
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_4           ; 28
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_5           ; 29
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_6           ; 2a
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_7           ; 2b
	const SPRITE_ANIM_FRAMESET_BLUE_WALK                 ; 2c
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_BLUE         ; 2d
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_SENT_BALL    ; 2e
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_OT_BALL      ; 2f
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_CABLE_BULGE  ; 30
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_SENT_PULSE   ; 31
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_OT_PULSE     ; 32
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_PING         ; 33
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE             ; 34
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_2           ; 35
	const SPRITE_ANIM_FRAMESET_INTRO_PICHU               ; 36
	const SPRITE_ANIM_FRAMESET_INTRO_WOOPER              ; 37
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_1             ; 38
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_2             ; 39
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_3             ; 3a
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_4             ; 3b
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F_2           ; 3c
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_AWAY        ; 3d
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F             ; 3e
	const SPRITE_ANIM_FRAMESET_CELEBI_LEFT               ; 3f
	const SPRITE_ANIM_FRAMESET_CELEBI_RIGHT              ; 40
DEF NUM_SPRITE_ANIM_FRAMESETS EQU const_value

; SpriteAnimOAMData indexes (see data/sprite_anims/oam.asm)
	const_def
	const SPRITE_ANIM_OAMSET_RED_WALK_1                  ; 00
	const SPRITE_ANIM_OAMSET_RED_WALK_2                  ; 01
	const SPRITE_ANIM_OAMSET_GS_INTRO_BUBBLE_1           ; 02
	const SPRITE_ANIM_OAMSET_GS_INTRO_BUBBLE_2           ; 03
	const SPRITE_ANIM_OAMSET_GS_INTRO_SHELLDER_1         ; 04
	const SPRITE_ANIM_OAMSET_GS_INTRO_SHELLDER_2         ; 05
	const SPRITE_ANIM_OAMSET_GS_INTRO_MAGIKARP_1         ; 06
	const SPRITE_ANIM_OAMSET_GS_INTRO_MAGIKARP_2         ; 07
	const SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_1           ; 08
	const SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_2           ; 09
	const SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_3           ; 0a
	const SPRITE_ANIM_OAMSET_GS_INTRO_NOTE               ; 0b
	const SPRITE_ANIM_OAMSET_GS_INTRO_INVISIBLE_NOTE     ; 0c
	const SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_1       ; 0d
	const SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_2       ; 0e
	const SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_3       ; 0f
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_1          ; 10
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_2          ; 11
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_3          ; 12
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_4          ; 13
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_1     ; 14
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_2     ; 15
	const SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_3     ; 16
	const SPRITE_ANIM_OAMSET_GS_INTRO_SMALL_FIREBALL     ; 17
	const SPRITE_ANIM_OAMSET_GS_INTRO_MED_FIREBALL       ; 18
	const SPRITE_ANIM_OAMSET_GS_INTRO_BIG_FIREBALL       ; 19
	const SPRITE_ANIM_OAMSET_GS_INTRO_CHIKORITA          ; 1a
	const SPRITE_ANIM_OAMSET_GS_INTRO_CYNDAQUIL          ; 1b
	const SPRITE_ANIM_OAMSET_GS_INTRO_TOTODILE           ; 1c
	const SPRITE_ANIM_OAMSET_GS_TITLE_TRAIL_1            ; 1d
	const SPRITE_ANIM_OAMSET_GS_TITLE_TRAIL_2            ; 1e
	const SPRITE_ANIM_OAMSET_TEXT_ENTRY_CURSOR           ; 1f
	const SPRITE_ANIM_OAMSET_TEXT_ENTRY_CURSOR_BIG       ; 20
	const SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO           ; 21
	const SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_STAR      ; 22
	const SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_1 ; 23
	const SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_2 ; 24
	const SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_3 ; 25
	const SPRITE_ANIM_OAMSET_SLOTS_GOLEM_1               ; 26
	const SPRITE_ANIM_OAMSET_SLOTS_GOLEM_2               ; 27
	const SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_1             ; 28
	const SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_2             ; 29
	const SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_3             ; 2a
	const SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_4             ; 2b
	const SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_5             ; 2c
	const SPRITE_ANIM_OAMSET_SLOTS_EGG                   ; 2d
	const SPRITE_ANIM_OAMSET_STILL_CURSOR                ; 2e
	const SPRITE_ANIM_OAMSET_TRADE_POKE_BALL_1           ; 2f
	const SPRITE_ANIM_OAMSET_TRADE_POKE_BALL_2           ; 30
	const SPRITE_ANIM_OAMSET_TRADE_POOF_1                ; 31
	const SPRITE_ANIM_OAMSET_TRADE_POOF_2                ; 32
	const SPRITE_ANIM_OAMSET_TRADE_POOF_3                ; 33
	const SPRITE_ANIM_OAMSET_TRADE_TUBE_BULGE_1          ; 34
	const SPRITE_ANIM_OAMSET_TRADE_TUBE_BULGE_2          ; 35
	const SPRITE_ANIM_OAMSET_TRADEMON_ICON_1             ; 36
	const SPRITE_ANIM_OAMSET_TRADEMON_ICON_2             ; 37
	const SPRITE_ANIM_OAMSET_TRADEMON_BUBBLE             ; 38
	const SPRITE_ANIM_OAMSET_EVOLUTION_BALL_OF_LIGHT_1   ; 39
	const SPRITE_ANIM_OAMSET_EVOLUTION_BALL_OF_LIGHT_2   ; 3a
	const SPRITE_ANIM_OAMSET_RADIO_TUNING_KNOB           ; 3b
	const SPRITE_ANIM_OAMSET_PARTY_MON_WITH_MAIL_1       ; 3c
	const SPRITE_ANIM_OAMSET_PARTY_MON_WITH_MAIL_2       ; 3d
	const SPRITE_ANIM_OAMSET_PARTY_MON_WITH_ITEM_1       ; 3e
	const SPRITE_ANIM_OAMSET_PARTY_MON_WITH_ITEM_2       ; 3f
	const SPRITE_ANIM_OAMSET_MAGNET_TRAIN_RED_1          ; 40
	const SPRITE_ANIM_OAMSET_MAGNET_TRAIN_RED_2          ; 41
	const SPRITE_ANIM_OAMSET_LEAF                        ; 42
	const SPRITE_ANIM_OAMSET_TREE_1                      ; 43
	const SPRITE_ANIM_OAMSET_CUT_TREE_2                  ; 44
	const SPRITE_ANIM_OAMSET_CUT_TREE_3                  ; 45
	const SPRITE_ANIM_OAMSET_CUT_TREE_4                  ; 46
	const SPRITE_ANIM_OAMSET_EGG_CRACK                   ; 47
	const SPRITE_ANIM_OAMSET_EGG_HATCH                   ; 48
	const SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_1      ; 49
	const SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_2      ; 4a
	const SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_3      ; 4b
	const SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_4      ; 4c
	const SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_5      ; 4d
	const SPRITE_ANIM_OAMSET_HEADBUTT_TREE_2             ; 4e
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_1             ; 4f
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_2             ; 50
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_3             ; 51
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_4             ; 52
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_5             ; 53
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_6             ; 54
	const SPRITE_ANIM_OAMSET_EZCHAT_CURSOR_7             ; 55
	const SPRITE_ANIM_OAMSET_BLUE_WALK_1                 ; 56
	const SPRITE_ANIM_OAMSET_BLUE_WALK_2                 ; 57
	const SPRITE_ANIM_OAMSET_MAGNET_TRAIN_BLUE_1         ; 58
	const SPRITE_ANIM_OAMSET_MAGNET_TRAIN_BLUE_2         ; 59
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_CABLE_BULGE_1  ; 5a
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_CABLE_BULGE_2  ; 5b
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_PING_1         ; 5c
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_PING_2         ; 5d
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_PING_3         ; 5e
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_SENT_PULSE     ; 5f
	const SPRITE_ANIM_OAMSET_MOBILE_TRADE_OT_PULSE       ; 60
	const SPRITE_ANIM_OAMSET_INTRO_SUICUNE_1             ; 61
	const SPRITE_ANIM_OAMSET_INTRO_SUICUNE_2             ; 62
	const SPRITE_ANIM_OAMSET_INTRO_SUICUNE_3             ; 63
	const SPRITE_ANIM_OAMSET_INTRO_SUICUNE_4             ; 64
	const SPRITE_ANIM_OAMSET_INTRO_PICHU_1               ; 65
	const SPRITE_ANIM_OAMSET_INTRO_PICHU_2               ; 66
	const SPRITE_ANIM_OAMSET_INTRO_PICHU_3               ; 67
	const SPRITE_ANIM_OAMSET_INTRO_WOOPER                ; 68
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_1               ; 69
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_2               ; 6a
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_3               ; 6b
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_F_2_1           ; 6c
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_F_2_2           ; 6d
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_F_2_3           ; 6e
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_F_2_4           ; 6f
	const SPRITE_ANIM_OAMSET_INTRO_UNOWN_F_2_5           ; 70
	const SPRITE_ANIM_OAMSET_INTRO_SUICUNE_AWAY          ; 71
	const SPRITE_ANIM_OAMSET_CELEBI_1                    ; 72
	const SPRITE_ANIM_OAMSET_CELEBI_2                    ; 73
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_1            ; 74
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_2            ; 75
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_3            ; 76
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_4            ; 77
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_5            ; 78
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_6            ; 79
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_7            ; 7a
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_8            ; 7b
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_9            ; 7c
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_10           ; 7d
	const SPRITE_ANIM_OAMSET_GAMEFREAK_LOGO_11           ; 7e
DEF NUM_SPRITE_ANIM_OAMSETS EQU const_value
