BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw TreeckoBitmasks
	dw GrovyleBitmasks
	dw SceptileBitmasks
	dw TorchicBitmasks
	dw CombuskenBitmasks
	dw BlazikenBitmasks
	dw MudkipBitmasks
	dw MarshtompBitmasks
	dw SwampertBitmasks
	dw PoochyenaBitmasks
	dw MightyenaBitmasks
	dw ZigzagoonBitmasks
	dw LinooneBitmasks
	dw WurmpleBitmasks
	dw SilcoonBitmasks
	dw BeautiflyBitmasks
	dw CascoonBitmasks
	dw DustoxBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw SeedotBitmasks
	dw NuzleafBitmasks
	dw ShiftryBitmasks
	dw TaillowBitmasks
	dw SwellowBitmasks
	dw WingullBitmasks
	dw PelipperBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw SurskitBitmasks
	dw MasquerainBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw SlakothBitmasks
	dw VigorothBitmasks
	dw SlakingBitmasks
	dw NincadaBitmasks
	dw NinjaskBitmasks
	dw ShedinjaBitmasks
	dw WhismurBitmasks
	dw LoudredBitmasks
	dw ExploudBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw AzurillBitmasks
	dw NosepassBitmasks
	dw SkittyBitmasks
	dw DelcattyBitmasks
	dw SableyeBitmasks
	dw MawileBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw MedititeBitmasks
	dw MedichamBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw PlusleBitmasks
	dw MinunBitmasks
	dw VolbeatBitmasks
	dw IllumiseBitmasks
	dw RoseliaBitmasks
	dw GulpinBitmasks
	dw SwalotBitmasks
	dw CarvanhaBitmasks
	dw SharpedoBitmasks
	dw WailmerBitmasks
	dw WailordBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw TorkoalBitmasks
	dw SpoinkBitmasks
	dw GrumpigBitmasks
	dw SpindaBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw CacneaBitmasks
	dw CacturneBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw ZangooseBitmasks
	dw SeviperBitmasks
	dw LunatoneBitmasks
	dw SolrockBitmasks
	dw BarboachBitmasks
	dw WhiscashBitmasks
	dw CorphishBitmasks
	dw CrawdauntBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw LileepBitmasks
	dw CradilyBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw CastformBitmasks
	dw KecleonBitmasks
	dw ShuppetBitmasks
	dw BanetteBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw TropiusBitmasks
	dw ChimechoBitmasks
	dw AbsolBitmasks
	dw WynautBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw SphealBitmasks
	dw SealeoBitmasks
	dw WalreinBitmasks
	dw ClamperlBitmasks
	dw HuntailBitmasks
	dw GorebyssBitmasks
	dw RelicanthBitmasks
	dw LuvdiscBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw RegirockBitmasks
	dw RegiceBitmasks
	dw RegisteelBitmasks
	dw LatiasBitmasks
	dw LatiosBitmasks
	dw KyogreBitmasks
	dw GroudonBitmasks
	dw RayquazaBitmasks
	dw JirachiBitmasks
	dw DeoxysBitmasks
	dw TurtwigBitmasks
	dw GrotleBitmasks
	dw TorterraBitmasks
	dw ChimcharBitmasks
	dw MonfernoBitmasks
	dw InfernapeBitmasks
	dw PiplupBitmasks
	dw PrinplupBitmasks
	dw EmpoleonBitmasks
	dw StarlyBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
	dw BidoofBitmasks
	dw BibarelBitmasks
	dw KricketotBitmasks
	dw KricketuneBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw BudewBitmasks
	dw RoseradeBitmasks
	dw CranidosBitmasks
	dw RampardosBitmasks
	dw ShieldonBitmasks
	dw BastiodonBitmasks
	dw BurmyBitmasks
	dw WormadamBitmasks
	dw MothimBitmasks
	dw CombeeBitmasks
	dw VespiquenBitmasks
	dw PachirisuBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw CherubiBitmasks
	dw CherrimBitmasks
	dw ShellosBitmasks
	dw GastrodonBitmasks
	dw AmbipomBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw GlameowBitmasks
	dw PuruglyBitmasks
	dw ChinglingBitmasks
	dw StunkyBitmasks
	dw SkuntankBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw HappinyBitmasks
	dw ChatotBitmasks
	dw SpiritombBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw MunchlaxBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw HippopotasBitmasks
	dw HippowdonBitmasks
	dw SkorupiBitmasks
	dw DrapionBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw CarnivineBitmasks
	dw FinneonBitmasks
	dw LumineonBitmasks
	dw MantykeBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw RhyperiorBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw PorygonZBitmasks
	dw GalladeBitmasks
	dw ProbopassBitmasks
	dw DusknoirBitmasks
	dw FroslassBitmasks
	dw RotomBitmasks
	dw UxieBitmasks
	dw MespritBitmasks
	dw AzelfBitmasks
	dw DialgaBitmasks
	dw PalkiaBitmasks
	dw HeatranBitmasks
	dw RegigigasBitmasks
	dw GiratinaBitmasks
	dw CresseliaBitmasks
	dw PhioneBitmasks
	dw ManaphyBitmasks
	dw DarkraiBitmasks
	dw ShayminBitmasks
	dw ArceusBitmasks
	dw SylveonBitmasks
	dw RegielekiBitmasks
	dw RegidragoBitmasks
	assert_table_length NUM_POKEMON
