FramesPointers:
	table_width 3, FramesPointers
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba FarfetchDFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba LickitungFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba JynxFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba CleffaFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba BellossomFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba PolitoedFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba MurkrowFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba UnownFrames
	dba WobbuffetFrames
	dba GirafarigFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba GligarFrames
	dba SteelixFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba DelibirdFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba SmeargleFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba SmoochumFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba TreeckoFrames
	dba GrovyleFrames
	dba SceptileFrames
	dba TorchicFrames
	dba CombuskenFrames
	dba BlazikenFrames
	dba MudkipFrames
	dba MarshtompFrames
	dba SwampertFrames
	dba PoochyenaFrames
	dba MightyenaFrames
	dba ZigzagoonFrames
	dba LinooneFrames
	dba WurmpleFrames
	dba SilcoonFrames
	dba BeautiflyFrames
	dba CascoonFrames
	dba DustoxFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba SeedotFrames
	dba NuzleafFrames
	dba ShiftryFrames
	dba TaillowFrames
	dba SwellowFrames
	dba WingullFrames
	dba PelipperFrames
	dba RaltsFrames
	dba KirliaFrames
	dba GardevoirFrames
	dba SurskitFrames
	dba MasquerainFrames
	dba ShroomishFrames
	dba BreloomFrames
	dba SlakothFrames
	dba VigorothFrames
	dba SlakingFrames
	dba NincadaFrames
	dba NinjaskFrames
	dba ShedinjaFrames
	dba WhismurFrames
	dba LoudredFrames
	dba ExploudFrames
	dba MakuhitaFrames
	dba HariyamaFrames
	dba AzurillFrames
	dba NosepassFrames
	dba SkittyFrames
	dba DelcattyFrames
	dba SableyeFrames
	dba MawileFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba MedititeFrames
	dba MedichamFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba PlusleFrames
	dba MinunFrames
	dba VolbeatFrames
	dba IllumiseFrames
	dba RoseliaFrames
	dba GulpinFrames
	dba SwalotFrames
	dba CarvanhaFrames
	dba SharpedoFrames
	dba WailmerFrames
	dba WailordFrames
	dba NumelFrames
	dba CameruptFrames
	dba TorkoalFrames
	dba SpoinkFrames
	dba GrumpigFrames
	dba SpindaFrames
	dba TrapinchFrames
	dba VibravaFrames
	dba FlygonFrames
	dba CacneaFrames
	dba CacturneFrames
	dba SwabluFrames
	dba AltariaFrames
	dba ZangooseFrames
	dba SeviperFrames
	dba LunatoneFrames
	dba SolrockFrames
	dba BarboachFrames
	dba WhiscashFrames
	dba CorphishFrames
	dba CrawdauntFrames
	dba BaltoyFrames
	dba ClaydolFrames
	dba LileepFrames
	dba CradilyFrames
	dba AnorithFrames
	dba ArmaldoFrames
	dba FeebasFrames
	dba MiloticFrames
	dba CastformFrames
	dba KecleonFrames
	dba ShuppetFrames
	dba BanetteFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba TropiusFrames
	dba ChimechoFrames
	dba AbsolFrames
	dba WynautFrames
	dba SnoruntFrames
	dba GlalieFrames
	dba SphealFrames
	dba SealeoFrames
	dba WalreinFrames
	dba ClamperlFrames
	dba HuntailFrames
	dba GorebyssFrames
	dba RelicanthFrames
	dba LuvdiscFrames
	dba BagonFrames
	dba ShelgonFrames
	dba SalamenceFrames
	dba BeldumFrames
	dba MetangFrames
	dba MetagrossFrames
	dba RegirockFrames
	dba RegiceFrames
	dba RegisteelFrames
	dba LatiasFrames
	dba LatiosFrames
	dba KyogreFrames
	dba GroudonFrames
	dba RayquazaFrames
	dba JirachiFrames
	dba DeoxysFrames
	dba TurtwigFrames
	dba GrotleFrames
	dba TorterraFrames
	dba ChimcharFrames
	dba MonfernoFrames
	dba InfernapeFrames
	dba PiplupFrames
	dba PrinplupFrames
	dba EmpoleonFrames
	dba StarlyFrames
	dba StaraviaFrames
	dba StaraptorFrames
	dba BidoofFrames
	dba BibarelFrames
	dba KricketotFrames
	dba KricketuneFrames
	dba ShinxFrames
	dba LuxioFrames
	dba LuxrayFrames
	dba BudewFrames
	dba RoseradeFrames
	dba CranidosFrames
	dba RampardosFrames
	dba ShieldonFrames
	dba BastiodonFrames
	dba BurmyFrames
	dba WormadamFrames
	dba MothimFrames
	dba CombeeFrames
	dba VespiquenFrames
	dba PachirisuFrames
	dba BuizelFrames
	dba FloatzelFrames
	dba CherubiFrames
	dba CherrimFrames
	dba ShellosFrames
	dba GastrodonFrames
	dba AmbipomFrames
	dba DrifloonFrames
	dba DrifblimFrames
	dba BunearyFrames
	dba LopunnyFrames
	dba MismagiusFrames
	dba HonchkrowFrames
	dba GlameowFrames
	dba PuruglyFrames
	dba ChinglingFrames
	dba StunkyFrames
	dba SkuntankFrames
	dba BronzorFrames
	dba BronzongFrames
	dba BonslyFrames
	dba MimeJrFrames
	dba HappinyFrames
	dba ChatotFrames
	dba SpiritombFrames
	dba GibleFrames
	dba GabiteFrames
	dba GarchompFrames
	dba MunchlaxFrames
	dba RioluFrames
	dba LucarioFrames
	dba HippopotasFrames
	dba HippowdonFrames
	dba SkorupiFrames
	dba DrapionFrames
	dba CroagunkFrames
	dba ToxicroakFrames
	dba CarnivineFrames
	dba FinneonFrames
	dba LumineonFrames
	dba MantykeFrames
	dba SnoverFrames
	dba AbomasnowFrames
	dba WeavileFrames
	dba MagnezoneFrames
	dba LickilickyFrames
	dba RhyperiorFrames
	dba TangrowthFrames
	dba ElectivireFrames
	dba MagmortarFrames
	dba TogekissFrames
	dba YanmegaFrames
	dba LeafeonFrames
	dba GlaceonFrames
	dba GliscorFrames
	dba MamoswineFrames
	dba PorygonZFrames
	dba GalladeFrames
	dba ProbopassFrames
	dba DusknoirFrames
	dba FroslassFrames
	dba RotomFrames
	dba UxieFrames
	dba MespritFrames
	dba AzelfFrames
	dba DialgaFrames
	dba PalkiaFrames
	dba HeatranFrames
	dba RegigigasFrames
	dba GiratinaFrames
	dba CresseliaFrames
	dba PhioneFrames
	dba ManaphyFrames
	dba DarkraiFrames
	dba ShayminFrames
	dba ArceusFrames
	dba SylveonFrames
	dba RegielekiFrames
	dba RegidragoFrames
	assert_table_length NUM_POKEMON
